//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP63_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public Avatar()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int IDAvatar { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
