//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP63_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public Avatar()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int IDAvatar { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
