//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP63_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreID { get; set; }
        public int Score1 { get; set; }
        public byte TailleJeu { get; set; }
        public byte NiveauDifficulte { get; set; }
        public Nullable<System.DateTime> DateScore { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
